language: scala

scala:
  - 2.12.7

jdk:
  - oraclejdk8


# https://travis-ci.community/t/solved-oraclejdk8-installation-failing-still-again/3428
dist: trusty


before_install:
  - git fetch --tags

stages:
  - name: clean
  - name: test
  - name: release
    if: (branch = master AND type = push) AND NOT fork

jobs:
  include:
    - stage: clean
      name: clean
      script: make deep_clean
    - stage: test
      name: compile
      script: sbt compile
    -
      name: scalafmt
      script: ./bin/scalafmt --test
    -
      name: mutators-test
      script: make mutator_test
      if: branch = master AND type = push AND NOT fork
    -
      name: unit-test
      script:
        - make test_coverage test_coverage_report
        - sbt coveralls
    - stage: release
      name: release-snapshot
      script: sbt 'set isSnapshot := true' "; project library ; ci-release"
      if: tag IS NOT present
    -
      name: release
      script: sbt "; project library ; ci-release"
      if: tag IS present

# https://github.com/olafurpg/sbt-ci-release/blob/master/.travis.yml

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
